#! /bin/sh
### BEGIN INIT INFO
# Provides:          HoCo Setup
# Required-Start:
# Required-Stop:
# Default-Start: 3
# Default-Stop:
# Short-Description: Starts next phase of HoCo setup
# Description:
### END INIT INFO

. /lib/lsb/init-functions

case "\$1" in
  start)
    log_daemon_msg "Starting HoCo Setup"
    . /opt/hoco/setup/status
    sudo su hoco -c "$HOCO_NEXT_SCRIPT |& tee -a /opt/hoco/setup/$HOCO_NEXT_SCRIPT.log"
    ;;
  *)
    echo "Usage: \$0 start" >&2
    exit 3
    ;;
esac
